### ISSUE TITLE
Missing Worldranking Data

### ISSUE THREAD

**Issue by NightwavesStudios** [speedclimbing/website#74]
<img width="778" alt="image" src="https://github.com/speedclimbing/website/assets/151556196/9dde72cd-eb0d-40b3-9283-b1326bc8908c">

World Ranking by Points and World Ranking by Average Rank are not showing data below them on the Statistics Summary (https://dev.speedclimbing.org/stats/summary?year=2024&gender=Male) Page.

**Comment by dorianim** [comment]
We don't have access to the latest data at the moment, unfortunately. I'll fix it once I find the time to do it.

**Comment by dorianim** [comment]
Should be fixed now.
